name: microkanren
version: '0.1.0.0'
maintainer: Justin Mimbs <justin.mimbs@gmail.com>
license: BSD3
github: justinmimbs/microkanren

dependencies:
  - base >= 4.9 && < 5
  - containers

library:
  source-dirs: src
  exposed-modules:
    - MicroKanren
    - MiniKanren

tests:
  spec:
    main: Main.hs
    source-dirs: test
    dependencies:
      - hspec
      - microkanren
